<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IL-IT-DHEERAJREDDY" failures="0" tests="5" name="com.unified.infinity.uitest.admin.UnifiedSignInUp" time="12.270" errors="1" timestamp="2023-02-21T17:38:38 IST" skipped="3">
  <testcase classname="com.unified.infinity.uitest.admin.UnifiedSignInUp" name="sendEmail" time="3.584">
    <error message="Cannot read the array length because &quot;a&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot read the array length because "a" is null
at java.base/java.util.Arrays.sort(Arrays.java:1233)
at com.unified.infinity.utils.DriverManager.sendEmail(DriverManager.java:207)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:400)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- sendEmail -->
  <system-out/>
  <testcase classname="com.unified.infinity.uitest.admin.UnifiedSignInUp" name="SignInwithInvalidPass" time="8.686"/>
  <system-out/>
  <testcase classname="com.unified.infinity.uitest.admin.UnifiedSignInUp" name="UnifiedOtp">
    <skipped/>
  </testcase> <!-- UnifiedOtp -->
  <system-out/>
  <testcase classname="com.unified.infinity.uitest.admin.UnifiedSignInUp" name="UnifiedForgotPass">
    <skipped/>
  </testcase> <!-- UnifiedForgotPass -->
  <system-out/>
  <testcase classname="com.unified.infinity.uitest.admin.UnifiedSignInUp" name="SignUP">
    <skipped/>
  </testcase> <!-- SignUP -->
  <system-out/>
</testsuite> <!-- com.unified.infinity.uitest.admin.UnifiedSignInUp -->
